---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data

```{r}
unzip("activity.zip")
rawData<-read.csv("activity.csv",stringsAsFactors = FALSE)
library("dplyr")
rawData<-tbl_df(rawData)
newData<-filter(rawData,!is.na(steps))

```


## What is mean total number of steps taken per day?

# For this part of the assignment, you can ignore the missing values in the dataset.

# 1. Calculate the total number of steps taken per day

DateData<-summarize(group_by(newData,date),sum=sum(steps),mean=mean(steps),median=median(steps))

# If you do not understand the difference between a histogram and a barplot, 
# research the difference between them. 

# 2. Make a histogram of the total number of steps taken each day

hist(DateData$sum,20)

# 3. Calculate and report the mean and median of the total number of steps taken per day

select(DateData,-sum)

# Date of data set: 2012/10/01 - 2012/11/30
# Number of days: 61
# Number of observations per day: 288 (Every 5 minutes = 12 times an hour for 24 hours)




use kable

2012-10-02 - 

 0   9 117 
286   1   1 

mean = 0.4375
median = 0

117 steps at interval 2210
9 steps at interval 2215

## What is the average daily activity pattern?

# Make a time series plot (i.e. type = "l") of the 5-minute interval (x-axis) 
# and the average number of steps taken, averaged across all days (y-axis)

IntervalData<-summarize(group_by(newData,interval),sum=sum(steps),mean=mean(steps),median=median(steps))

plot(IntervalData$interval,IntervalData$mean,type="l")

# Which 5-minute interval, on average across all the days in the dataset, 
# contains the maximum number of steps?

arrange(IntervalData,desc(sum))[1,1]

## Imputing missing values

# Note that there are a number of days/intervals where there are missing values 
# (coded as NA). The presence of missing days may introduce bias into some 
# calculations or summaries of the data.

# Calculate and report the total number of missing values in the dataset 
# (i.e. the total number of rows with NAs)

Count<-table(is.na(rawData$steps))
Count[names(Count)==TRUE]

# Devise a strategy for filling in all of the missing values in the dataset. 
# The strategy does not need to be sophisticated. For example, you could 
# use the mean/median for that day, or the mean for that 5-minute interval, etc.

# Create a new dataset that is equal to the original dataset but with the 
# missing data filled in.

rawData2<-rawData
rawLength<-dim(rawData2)[1]
for (i in 1:rawLength){
  x<-i%%288
  if (x==0){x<-288}
  if (is.na(rawData2$step[i])==TRUE){
    rawData2$steps[i]<-IntervalData$mean[x]
  }
}

# Make a histogram of the total number of steps taken each day and Calculate 
# and report the mean and median total number of steps taken per day. 

DateData2<-summarize(group_by(rawData2,date),sum=sum(steps),mean=mean(steps),median=median(steps))

hist(DateData2$sum,20)

select(DateData2,-sum)

# Do these 
# values differ from the estimates from the first part of the assignment? 
# What is the impact of imputing missing data on the estimates of the total daily number of steps?


## Are there differences in activity patterns between weekdays and weekends?

# For this part the weekdays() function may be of some help here. Use the 
# dataset with the filled-in missing values for this part.

# Create a new factor variable in the dataset with two levels – “weekday” and 
# “weekend” indicating whether a given date is a weekday or weekend day.

DayData<-mutate(rawData2,Day=wday(rawData2$date),Weekday=Day!=1&Day!=7)
WeekdayData<-DayData[DayData$Weekday,]
WDayIntData<-summarize(group_by(WeekdayData,interval),sum=sum(steps),mean=mean(steps),median=median(steps))
plot(WDayIntData$interval,WDayIntData$mean,type="l")

WeekendData<-DayData[!DayData$Weekday,]
WEndIntData<-summarize(group_by(WeekendData,interval),sum=sum(steps),mean=mean(steps),median=median(steps))
plot(WEndIntData$interval,WEndIntData$mean,type="l")


# Make a panel plot containing a time series plot (i.e. type = "l") of the 
# 5-minute interval (x-axis) and the average number of steps taken, averaged 
# across all weekday days or weekend days (y-axis). See the README file in 
# the GitHub repository to see an example of what this plot should look like using simulated data.
